import { Link } from 'react-router-dom';
import { ExternalLink as Ext, MailLink } from './LegalLinks';
import { DIGGLE_LEGAL, type DiggleDocType, type LegalDocument } from './diggleLegal';

// Diggle's legal documents, as data (types and dates: diggleLegal.ts).
// Two renderers read this:
//   - src/diggle/legal/DiggleLegalPage.tsx — the themed /diggle/* pages
//   - src/policies/DigglePolicies.tsx — the registry components
// Every factual claim was checked against the game's main branch and the
// live candy guard on 2026-10-04. Re-check before changing what a section
// says the game collects, stores or charges.

const { company: COMPANY, email: EMAIL, packageId: PACKAGE_ID, governingLaw: LAW } = DIGGLE_LEGAL;


// ── Privacy ─────────────────────────────────────────────────────────

const privacy: LegalDocument = {
  title: 'Privacy Policy',
  tab: 'Privacy',
  lede: (
    <p>
      Diggle is published by <strong>{COMPANY}</strong> ("we", "us"). This policy explains what the game and its
      website collect, why, who else handles it, and what you can do about it. It covers the Diggle app on the Solana
      dApp Store (<code>{PACKAGE_ID}</code>) and the Diggle pages of this website, including minting a Diggle Machine.
    </p>
  ),
  summary: [
    <>
      You can play as a <strong>guest</strong>. Signing in with an email address or a Solana wallet is optional, and
      lets your progress follow you between devices.
    </>,
    <>
      We store your progress on <strong>our servers</strong> &mdash; saves, stats, quests and the record of points
      you earn and spend &mdash; so it syncs and so the leaderboards work.
    </>,
    <>
      We only ever see <strong>public wallet addresses</strong>. We never see, ask for or store your private keys or
      recovery phrase.
    </>,
    <>
      Blockchain transactions are <strong>public and permanent</strong>. Nobody, including us, can delete them.
    </>,
    <>
      Diggle has <strong>no ads and no analytics or tracking SDKs</strong>, and we don't sell personal information.
    </>,
  ],
  sections: [
    {
      id: 'sign-in',
      title: 'How you play and sign in',
      body: (
        <>
          <ul>
            <li>
              <strong>As a guest.</strong> On first launch the app creates a random identifier and an anonymous
              account, so you can play straight away without giving us anything about yourself. The identifier is
              generated by the app; it is not your device's hardware ID or advertising ID.
            </li>
            <li>
              <strong>With email.</strong> If you choose email sign-in, we store your email address. Your password is
              handled by our authentication provider (Supabase Auth) and stored hashed &mdash; never in plain text, and
              never visible to us.
            </li>
            <li>
              <strong>With a Solana wallet.</strong> Your wallet app signs a one-time message to prove you control the
              address. We store the wallet address. The one-time code in that message is deleted as soon as it's used,
              or after five minutes. Signing in costs nothing and is not a transaction.
            </li>
          </ul>
          <p>You can link more than one sign-in method to the same player from the Account screen.</p>
        </>
      ),
    },
    {
      id: 'server-data',
      title: 'What we store on our servers',
      body: (
        <>
          <table className="policy-table">
            <thead>
              <tr>
                <th>Information</th>
                <th>Why</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Player ID, the guest identifier, how you sign in, and when your account was created and last used</td>
                <td>To identify your player and keep you signed in</td>
              </tr>
              <tr>
                <td>Email address (email sign-in only)</td>
                <td>To sign you in and to answer requests about your account</td>
              </tr>
              <tr>
                <td>Wallet address (wallet sign-in or a linked wallet)</td>
                <td>
                  To sign you in, to check which Diggle Machines and Seeker Genesis Token you hold, and to match Miner's
                  Pass payments to your player
                </td>
              </tr>
              <tr>
                <td>Display name, if you set one</td>
                <td>Shown on the leaderboards</td>
              </tr>
              <tr>
                <td>
                  Progress and stats: XP, level, points, cash earned, deepest depth, ores mined, play time, prestige
                  level, login streak, quest progress and weekly challenge scores
                </td>
                <td>To sync your progress and run quests, streaks and leaderboards</td>
              </tr>
              <tr>
                <td>World saves: the world seed, a compressed copy of the map, your position and your rig's systems</td>
                <td>So you can continue a run, including on another device</td>
              </tr>
              <tr>
                <td>A record of every change to your points, with its source and time</td>
                <td>To keep an accurate balance and to investigate errors</td>
              </tr>
              <tr>
                <td>The Diggle Machine you equip and its traits</td>
                <td>To apply its in-game bonuses</td>
              </tr>
              <tr>
                <td>Fair-play flags raised by our automated checks, with the reason and supporting details</td>
                <td>To protect the leaderboards and the game's economy from cheating</td>
              </tr>
              <tr>
                <td>Miner's Pass orders: the paying wallet, the SKR amount, the transaction signature and the week granted</td>
                <td>To confirm your payment and grant the pass</td>
              </tr>
            </tbody>
          </table>
          <p>
            Our backend provider also keeps standard request logs &mdash; IP address, time and request &mdash; for
            security and troubleshooting.
          </p>
        </>
      ),
    },
    {
      id: 'on-device',
      title: 'What stays on your device',
      body: (
        <p>
          The app keeps some things only on your device: your settings (sound, language and visual effects level), your
          save slots, how far you are through the tutorial tips, whether the app has asked you for a review, your
          achievements and museum collection, which machine you have equipped, and cached details of your Diggle
          Machines. This isn't sent to us, and it's removed when you uninstall the app.
        </p>
      ),
    },
    {
      id: 'wallets',
      title: 'Wallets and the blockchain',
      body: (
        <ul>
          <li>
            Diggle connects to your wallet through the Solana Mobile Wallet Adapter on your phone, or through a browser
            wallet on this website. Your wallet app is provided by someone else, under its own terms and privacy
            policy. You approve every signature in the wallet itself.
          </li>
          <li>
            To show your Diggle Machines, your Seeker Genesis Token and your balances, the app and the website read
            public blockchain data through Solana RPC providers. The provider receives your wallet address and IP address
            with each request. The app uses Solana's public RPC service; the website uses PublicNode or another provider
            we configure.
          </li>
          <li>
            Diggle Machine images and metadata are stored on Arweave, a permanent public storage network, and are
            fetched through public gateways that see your IP address.
          </li>
          <li>
            Mints and Miner's Pass payments are blockchain transactions. Your wallet address, the amounts and the
            transaction itself are recorded publicly and permanently on Solana. We cannot change or delete them, and
            the deletion rights below don't reach them.
          </li>
        </ul>
      ),
    },
    {
      id: 'social-quests',
      title: 'Social quests',
      body: (
        <>
          <p>These quests are optional.</p>
          <ul>
            <li>
              <strong>Join the Discord.</strong> You sign in with Discord using the <code>identify</code> permission
              only. We use your Discord user ID once, to check that you're a member of the Diggle server, and record
              that the quest is complete. We don't store your Discord ID or username.
            </li>
            <li>
              <strong>Post on X.</strong> You paste the link to your post. We send it to X's public embed service to
              confirm the post exists and mentions Diggle, then record the quest as complete. We don't store the link.
            </li>
            <li>
              <strong>Follow on X.</strong> This opens X. Nothing is checked, and nothing is stored beyond the quest
              being marked complete.
            </li>
          </ul>
        </>
      ),
    },
    {
      id: 'website',
      title: 'This website',
      body: (
        <ul>
          <li>The Diggle pages don't use cookies, analytics or advertising trackers.</li>
          <li>
            When you connect a wallet, the wallet adapter remembers which wallet you chose in your browser's local
            storage, so it can reconnect next time. Clearing this site's data removes it.
          </li>
          <li>
            Your balance and how many machines you've minted are read from the blockchain in your browser; they aren't
            sent to us. Minting happens between your wallet and the Solana network.
          </li>
          <li>
            The site is hosted by Vercel, which keeps standard request logs (IP address, browser and time). Fonts are
            served from this site, not from a third-party font service.
          </li>
        </ul>
      ),
    },
    {
      id: 'who-else',
      title: 'Who else handles data',
      body: (
        <ul>
          <li>
            <strong>Supabase</strong> hosts our database, sign-in and server functions, and processes the server-side
            data above on our behalf. <Ext href="https://supabase.com/privacy">Privacy policy</Ext>
          </li>
          <li>
            <strong>Solana RPC providers</strong> &mdash; the Solana Foundation's public service (in the app) and
            PublicNode (on the website) &mdash; relay your requests to the blockchain.{' '}
            <Ext href="https://solana.com/privacy-policy">Solana Foundation</Ext> &middot;{' '}
            <Ext href="https://publicnode.com/privacy">PublicNode</Ext>
          </li>
          <li>
            <strong>Solana Mobile</strong> distributes Diggle through the dApp Store, including any reviews you post
            there. <Ext href="https://legal.solanamobile.com/privacy-policy">Privacy policy</Ext>
          </li>
          <li>
            <strong>Discord</strong> and <strong>X</strong>, only if you use the social quests.{' '}
            <Ext href="https://discord.com/privacy">Discord</Ext> &middot;{' '}
            <Ext href="https://x.com/en/privacy">X</Ext>
          </li>
          <li>
            <strong>Vercel</strong> hosts this website.{' '}
            <Ext href="https://vercel.com/legal/privacy-notice">Privacy notice</Ext>
          </li>
          <li>
            <strong>Arweave gateways</strong> serve Diggle Machine images and metadata, and <strong>your wallet
            provider</strong> handles your keys and signatures, each under their own policies.
          </li>
        </ul>
      ),
    },
    {
      id: 'how-we-use-it',
      title: 'How we use information',
      body: (
        <>
          <p>
            To run the game and sync your progress; to sign you in; to run quests, streaks, weekly challenges and
            leaderboards; to apply gear bonuses and confirm purchases; to detect and prevent cheating, farming and
            abuse; and to answer support requests and comply with the law.
          </p>
          <p>
            We don't use it for advertising, we don't build advertising profiles, and we don't sell or rent it to
            anyone.
          </p>
        </>
      ),
    },
    {
      id: 'public',
      title: 'What other players can see',
      body: (
        <p>
          Leaderboards show your display name (or "Anonymous Miner" if you haven't set one), your deepest depth, your
          lifetime points earned and your lifetime cash earned. Accounts flagged by our fair-play checks are left off
          the leaderboards. Anything on the blockchain &mdash; your wallet address, the machines it holds and your
          transactions &mdash; is visible to everyone.
        </p>
      ),
    },
    {
      id: 'retention',
      title: 'How long we keep it',
      body: (
        <ul>
          <li>Your account, progress, saves and quests: for as long as your account exists.</li>
          <li>
            Your points record and any fair-play flags: for as long as your account exists and, after it's deleted,
            only where we need them to resolve a dispute, prevent abuse or meet a legal obligation.
          </li>
          <li>Wallet sign-in codes: deleted when used, or after five minutes.</li>
          <li>Social-quest links and Discord IDs: not stored.</li>
          <li>Request logs: kept by Supabase and Vercel under their own retention policies.</li>
        </ul>
      ),
    },
    {
      id: 'deleting',
      title: 'Deleting your account',
      body: (
        <>
          <p>
            The app doesn't have a delete button yet. Email <MailLink email={EMAIL} /> from the address you sign in with, or include your
            player ID (you can copy it from the Account screen) and any wallet address linked to it. We'll confirm the
            request is yours &mdash; for a wallet-only account we may ask you to sign a message with that wallet
            &mdash; then delete your player record, profile, saves, stats, quests and gear records within 30 days and
            tell you when it's done.
          </p>
          <p>
            Blockchain records can't be deleted, and anything in your wallet, including Diggle Machines, stays yours.
          </p>
        </>
      ),
    },
    {
      id: 'children',
      title: 'Children',
      body: (
        <p>
          Diggle is for players aged 13 and over, and its wallet features &mdash; connecting a wallet, buying the
          Miner's Pass and minting &mdash; are for adults (18, or the age of majority where you live). We don't
          knowingly collect personal information from children under 13. If you believe a child has given us personal
          information, email <MailLink email={EMAIL} /> and we'll delete it.
        </p>
      ),
    },
    {
      id: 'your-rights',
      title: 'Your rights',
      body: (
        <>
          <p>
            Depending on where you live, you may have the right to access, correct, delete or export the personal
            information we hold about you, and to object to how we use it. Email <MailLink email={EMAIL} />.
          </p>
          <p>
            <strong>EEA and UK players:</strong> we process your information to provide the game and the account you
            asked for (performance of a contract), and for our legitimate interests in keeping Diggle secure and fair
            and in improving it.
          </p>
          <p>
            <strong>California players:</strong> we don't sell personal information, and we don't share it for
            cross-context behavioural advertising.
          </p>
        </>
      ),
    },
    {
      id: 'popia',
      title: 'South Africa and POPIA',
      body: (
        <>
          <p>
            We are based in {LAW}, so the Protection of Personal Information Act 4 of 2013 ("POPIA") applies.{' '}
            {COMPANY} is the <strong>responsible party</strong> for the processing described here. Supabase and Vercel
            process information on our behalf as our <strong>operators</strong>. RPC providers, Solana Mobile, Discord,
            X and wallet providers decide their own purposes and means, so they are responsible parties in their own
            right.
          </p>
          <p>
            Under POPIA you may ask us to confirm what personal information we hold about you, to correct or delete it,
            and you may object to processing. Write to <MailLink email={EMAIL} />. If you're not satisfied with how we handle a request,
            you may complain to the{' '}
            <Ext href="https://inforegulator.org.za">Information Regulator (South Africa)</Ext>.
          </p>
        </>
      ),
    },
    {
      id: 'transfers',
      title: 'Where information is processed',
      body: (
        <p>
          Our providers may store and process information outside South Africa, including in the United States and the
          European Union. Where that happens, we rely on providers bound by data-protection terms that give it a level
          of protection comparable to POPIA.
        </p>
      ),
    },
    {
      id: 'security',
      title: 'Security',
      body: (
        <p>
          Traffic between the app, this website and our servers is encrypted (HTTPS/TLS). Database access rules mean
          each player's session can only read its own data. Wallet sign-in uses a signature rather than a password. No
          method of transmission or storage is perfectly secure, and we can't guarantee absolute security.
        </p>
      ),
    },
    {
      id: 'changes',
      title: 'Changes',
      body: (
        <p>
          If this policy changes materially, we'll update the dates at the top and publish the new version at this
          address before the change takes effect.
        </p>
      ),
    },
    {
      id: 'contact',
      title: 'Contact',
      body: (
        <p>
          <strong>{COMPANY}</strong>
          <br />
          <MailLink email={EMAIL} />
        </p>
      ),
    },
  ],
};

// ── Terms ───────────────────────────────────────────────────────────

const terms: LegalDocument = {
  title: 'Terms & Conditions',
  tab: 'Terms',
  lede: (
    <>
      <p>
        These terms are an agreement between you and <strong>{COMPANY}</strong> ("we", "us") for your use of Diggle
        &mdash; the game on the Solana dApp Store and the Diggle pages of this website, including the Diggle Machine
        mint. By playing, signing in or minting, you accept them. If you don't accept them, don't use Diggle.
      </p>
      <p>
        Our <Link to="/diggle/privacy">Privacy Policy</Link> explains what Diggle collects and who receives it. It forms
        part of these terms.
      </p>
    </>
  ),
  sections: [
    {
      id: 'eligibility',
      title: '1. Who may use Diggle',
      body: (
        <ul>
          <li>You must be <strong>13 or over</strong> to play.</li>
          <li>
            Connecting a wallet, buying the Miner's Pass and minting Diggle Machines are for adults: you must be{' '}
            <strong>18, or the age of majority where you live</strong>, whichever is higher.
          </li>
          <li>
            Don't use Diggle where doing so is against the law where you are, including if sanctions laws prohibit you
            from dealing with us.
          </li>
        </ul>
      ),
    },
    {
      id: 'accounts',
      title: '2. Your account and your wallet',
      body: (
        <ul>
          <li>
            You can play as a guest, or sign in with an email address or a Solana wallet. Keep your sign-in details
            secure; you're responsible for what happens on your account.
          </li>
          <li>
            Guest progress belongs to an anonymous account on your device. If you uninstall before signing in, it may be
            lost.
          </li>
          <li>
            Your wallet is self-custodial. We never hold your keys, we can't access your wallet, and we can't recover
            lost keys or reverse transactions.
          </li>
          <li>
            <strong>We will never ask for your recovery phrase or private key.</strong> Anyone who does &mdash; in
            Discord, on X or in a direct message &mdash; is not us.
          </li>
        </ul>
      ),
    },
    {
      id: 'licence',
      title: '3. Your licence to play',
      body: (
        <p>
          We grant you a personal, non-exclusive, non-transferable, revocable licence to install and play Diggle on
          devices you control, for your own personal, non-commercial use. Diggle Machine NFTs are covered separately in
          section 7.
        </p>
      ),
    },
    {
      id: 'fair-play',
      title: '4. Fair play',
      body: (
        <>
          <p>You may not:</p>
          <ul>
            <li>use a modified client, bot, script, macro or memory editor, or otherwise automate play;</li>
            <li>farm points or other rewards, or use several accounts to multiply them;</li>
            <li>exploit bugs or errors instead of reporting them;</li>
            <li>interfere with our servers, the leaderboards, other players or our verification systems;</li>
            <li>reverse engineer the app, except where that right can't lawfully be excluded;</li>
            <li>use Diggle to break the law.</li>
          </ul>
          <p>
            Diggle runs automated checks on how points are earned. If they flag your account, or we reasonably believe
            you've broken this section, we may leave you off the leaderboards and weekly challenges, reverse or adjust
            progress, points or rewards gained improperly, and suspend or close the account. If you think a flag is a
            mistake, email <MailLink email={EMAIL} /> and a person will review it.
          </p>
        </>
      ),
    },
    {
      id: 'points',
      title: '5. Points, cash and in-game items',
      body: (
        <>
          <p>
            <strong>
              XP, points, in-game cash, upgrades, consumables and other in-game items are features of the game. They are
              not property, they have no monetary value, and they can't be sold, transferred to another player or
              redeemed for money.
            </strong>
          </p>
          <p>
            We may adjust balances to correct errors, bugs or abuse, and we may change how points are earned and what
            they can be spent on.
          </p>
          <p>
            From time to time we may run promotions, events or other reward programs. Taking part is optional, each one
            is at our discretion, and each runs on the rules we publish for it at the time.
          </p>
        </>
      ),
    },
    {
      id: 'miners-pass',
      title: "6. The Miner's Pass",
      body: (
        <ul>
          <li>
            Where it's offered, the Miner's Pass is a weekly pass paid in SKR, the Solana Mobile ecosystem token.
            Payment is a token transfer from your wallet that you approve in the wallet; the price is shown before you
            sign.
          </li>
          <li>
            Once the transfer is confirmed on the blockchain, the pass is granted for the week shown. Blockchain
            transfers are final: we can't reverse them, and the pass isn't refundable except where the law where you
            live requires otherwise.
          </li>
          <li>We may change the price for future weeks, or stop offering the pass.</li>
        </ul>
      ),
    },
    {
      id: 'nfts',
      title: '7. Diggle Machine NFTs',
      body: (
        <>
          <p>
            <strong>What you get.</strong> A Diggle Machine is an NFT on the Solana blockchain, from a collection of
            10,000. When you mint or buy one, you own that token, and the game recognises it as gear when the holding
            wallet is connected.
          </p>
          <p>
            <strong>Sealed until reveal.</strong> Every machine mints as a sealed crate. Its five parts are revealed
            when the collection mints out, using a mapping whose hash is published in the candy machine's on-chain
            settings so the reveal can be checked against it. We don't promise when the collection will mint out.
          </p>
          <p>
            <strong>In-game gear.</strong> A revealed machine's parts give the in-game bonuses described on the Diggle
            site, and a sealed crate gives a holder bonus (currently +25% XP and points). Gear never applies in the
            weekly challenge, which uses a standard loadout. We may rebalance or change gear and holder bonuses as the
            game develops, and we don't promise that any particular bonus will last.
          </p>
          <p>
            <strong>Minting is final.</strong> Each mint costs the price shown when you mint (currently 0.1 SOL), plus
            network fees and rent, paid from your wallet. A per-wallet limit applies. Completed mints aren't refundable
            except where the law requires.
          </p>
          <p>
            <strong>Bot tax.</strong> The candy machine has a bot-tax guard: a mint transaction that breaks one of the
            mint rules &mdash; for example, by going over the wallet limit &mdash; is charged a small fee (currently 0.01
            SOL) and no machine is created. Our mint page checks the rules first to avoid this; third-party tools may
            not.
          </p>
          <p>
            <strong>Resale.</strong> You can sell or transfer your machine on marketplaces that support it. The
            collection sets a 5% creator royalty; each marketplace decides whether to enforce it. Marketplaces and
            wallets are third-party services we don't control.
          </p>
          <p>
            <strong>Artwork licence.</strong> {COMPANY} keeps the copyright in all Diggle Machine artwork. While you own
            a machine, you may display its artwork and use it as a profile picture or avatar, for personal,
            non-commercial purposes. You may not use it to sell goods or services, in advertising, or to make
            derivative collections. This licence passes to the machine's next owner, and ends for you when you transfer
            it.
          </p>
          <p>
            <strong>Not an investment.</strong> Diggle Machines are in-game gear and collectibles. We don't promise
            they will have or keep any value, and nothing we say is an offer or a promise of financial return. Don't
            buy one unless you're comfortable with what it is today.
          </p>
        </>
      ),
    },
    {
      id: 'blockchain-risks',
      title: '8. Blockchain risks',
      body: (
        <ul>
          <li>Blockchain transactions are irreversible. Check every transaction in your wallet before you approve it.</li>
          <li>Network fees vary, and congestion, outages or RPC failures can delay a transaction or make it fail.</li>
          <li>
            The mint uses Metaplex's candy machine programs, which are operated by third parties and run on a network
            we don't control.
          </li>
          <li>The value of SOL and SKR can change quickly, and laws about digital assets can change.</li>
          <li>You're responsible for any taxes on your own transactions.</li>
        </ul>
      ),
    },
    {
      id: 'conduct',
      title: '9. Display names and conduct',
      body: (
        <p>
          Don't choose a display name that is offensive, impersonates someone, or is misleading. We may change or remove
          a display name that breaks this rule. Be decent in Diggle's community spaces; the Discord also has its own
          rules.
        </p>
      ),
    },
    {
      id: 'third-parties',
      title: '10. Third-party services',
      body: (
        <p>
          Wallets, the Solana dApp Store, Discord, X, NFT marketplaces and RPC providers are run by other companies under
          their own terms. We aren't responsible for them, and your use of them is between you and them.
        </p>
      ),
    },
    {
      id: 'availability',
      title: '11. Availability and changes',
      body: (
        <>
          <p>
            Diggle is free to play. Gameplay works offline, but syncing, leaderboards, quests, sign-in and purchases
            need a network connection.
          </p>
          <p>
            We may update, change or discontinue Diggle or any of its features. We won't do that as a way of avoiding an
            obligation we already owe you, and where we withdraw a paid feature you've bought, we'll act reasonably
            about it.
          </p>
        </>
      ),
    },
    {
      id: 'ip',
      title: '12. Our intellectual property',
      body: (
        <p>
          Diggle &mdash; its code, artwork, sound, name and design &mdash; belongs to <strong>{COMPANY}</strong> or its
          licensors and is protected by copyright and other laws. Nothing in these terms transfers any of it to you
          beyond the licences in sections 3 and 7. You may freely record, stream and publish footage of your own play,
          including monetised video.
        </p>
      ),
    },
    {
      id: 'disclaimers',
      title: '13. Disclaimers',
      body: (
        <>
          <p>
            Diggle is provided <strong>"as is"</strong>. To the fullest extent the law allows, we exclude implied
            warranties of merchantability, fitness for a particular purpose and non-infringement, and we don't warrant
            that Diggle will be uninterrupted or error-free, or that progress will never be lost.
          </p>
          <p>
            Nothing here excludes liability that can't lawfully be excluded, including for death or personal injury
            caused by negligence, or for fraud. If you're a consumer, you keep all the statutory rights your local law
            gives you, and where those rights conflict with this section, they win.
          </p>
        </>
      ),
    },
    {
      id: 'liability',
      title: '14. Limitation of liability',
      body: (
        <>
          <p>
            To the fullest extent the law allows, and subject to section 13, we aren't liable for indirect or
            consequential loss; loss of data or progress; loss of profit or opportunity; changes in the market value of
            any digital asset; or losses caused by the security of your own wallet or device.
          </p>
          <p>
            Where we are liable, our total liability to you is limited to the greater of the amount you paid us in the
            twelve months before the claim, or USD 50.
          </p>
        </>
      ),
    },
    {
      id: 'termination',
      title: '15. Ending this agreement',
      body: (
        <p>
          You may stop using Diggle at any time, and ask us to delete your account as described in the{' '}
          <Link to="/diggle/privacy">Privacy Policy</Link>. We may suspend or end your access if you materially break
          these terms, in particular section 4. Diggle Machines in your wallet stay yours either way. Sections 5, 7,
          8, 12, 13, 14 and 16 survive the end of this agreement.
        </p>
      ),
    },
    {
      id: 'law',
      title: '16. Governing law and disputes',
      body: (
        <p>
          These terms are governed by the laws of <strong>{LAW}</strong>, and the courts of {LAW} have jurisdiction. If
          you're a consumer living elsewhere, this doesn't take away the protection of the mandatory consumer law of the
          country you live in, or your right to bring proceedings there.
        </p>
      ),
    },
    {
      id: 'changes',
      title: '17. Changes to these terms',
      body: (
        <p>
          We may update these terms. If a change materially affects your rights, we'll update the dates at the top and
          publish the new version here before it takes effect. Continuing to use Diggle after that means you accept the
          new version.
        </p>
      ),
    },
    {
      id: 'contact',
      title: '18. Contact',
      body: (
        <p>
          <strong>{COMPANY}</strong>
          <br />
          <MailLink email={EMAIL} />
        </p>
      ),
    },
  ],
};

// ── License ─────────────────────────────────────────────────────────

const license: LegalDocument = {
  title: 'License Agreement',
  tab: 'License',
  lede: (
    <p>
      This End User License Agreement is between you and <strong>{COMPANY}</strong> for the Diggle mobile game (
      <code>{PACKAGE_ID}</code>). It supplements the <Link to="/diggle/terms">Terms &amp; Conditions</Link>, which
      win if the two conflict.
    </p>
  ),
  sections: [
    {
      id: 'grant',
      title: '1. Grant of licence',
      body: (
        <p>
          We grant you a revocable, non-exclusive, non-transferable, limited licence to download, install and use Diggle
          on devices you control, solely for your personal, non-commercial purposes and in accordance with this
          Agreement.
        </p>
      ),
    },
    {
      id: 'restrictions',
      title: '2. Restrictions',
      body: (
        <>
          <p>You agree not to, and not to let others:</p>
          <ul>
            <li>license, sell, rent, lease, assign, distribute, host or otherwise commercially exploit the app;</li>
            <li>
              modify, make derivative works of, disassemble, decrypt or reverse engineer any part of the app, except
              where that right can't lawfully be excluded;
            </li>
            <li>use a modified client, bot, script, macro or memory editor to alter or automate play;</li>
            <li>remove, obscure or alter any copyright, trademark or other proprietary notice.</li>
          </ul>
        </>
      ),
    },
    {
      id: 'virtual-items',
      title: '3. Points and in-game items',
      body: (
        <p>
          XP, points, in-game cash and other in-game items have no monetary value and can't be sold, transferred or
          redeemed for money. Section 5 of the <Link to="/diggle/terms">Terms &amp; Conditions</Link> sets this out in
          full.
        </p>
      ),
    },
    {
      id: 'nft-art',
      title: '4. Diggle Machine artwork',
      body: (
        <p>
          Owning a Diggle Machine gives you a personal, non-commercial licence to display its artwork, described in
          section 7 of the <Link to="/diggle/terms">Terms &amp; Conditions</Link>. It doesn't transfer copyright.
        </p>
      ),
    },
    {
      id: 'streaming',
      title: '5. Streaming and video',
      body: (
        <p>
          You may record, stream and publish footage of your own play, including monetised video, without a separate
          licence from us.
        </p>
      ),
    },
    {
      id: 'termination',
      title: '6. Termination',
      body: (
        <p>
          This Agreement lasts until you or we end it. Your rights under it end automatically, without notice, if you
          fail to comply with any of its terms. When it ends, you must stop using the app and delete it from your
          devices.
        </p>
      ),
    },
    {
      id: 'grants',
      title: '7. Permissions and grants',
      body: (
        <p>
          <strong>{COMPANY}</strong> grants Solana Mobile the right to display all media submitted to the Solana dApp
          Store &mdash; screenshots, video, icon and banner &mdash; for the purpose of showcasing this application.
        </p>
      ),
    },
  ],
};

// ── Copyright ───────────────────────────────────────────────────────

const copyright: LegalDocument = {
  title: 'Copyright Notice',
  tab: 'Copyright',
  lede: (
    <p>
      <strong>
        Copyright &copy; {new Date().getFullYear()} {COMPANY}. All rights reserved.
      </strong>
    </p>
  ),
  sections: [
    {
      id: 'ownership',
      title: 'Ownership',
      body: (
        <p>
          Diggle, including all of its content, features and functionality &mdash; software, text, images, animation
          and audio, and their design, selection and arrangement &mdash; is owned by {COMPANY}, its licensors or other
          providers of that material, and is protected by copyright and other laws.
        </p>
      ),
    },
    {
      id: 'art',
      title: 'Game and collection art',
      body: (
        <p>
          The pixel art in Diggle &mdash; the terrain and ores, the starter rig, every Diggle Machine part and its
          animation, and the collection artwork &mdash; is original work created by {COMPANY}.
        </p>
      ),
    },
    {
      id: 'holders',
      title: 'Diggle Machine holders',
      body: (
        <p>
          Owning a Diggle Machine means owning that token. {COMPANY} keeps the copyright in its artwork; holders get the
          personal-use licence set out in section 7 of the <Link to="/diggle/terms">Terms &amp; Conditions</Link>. You
          don't need to own a Diggle Machine to play Diggle.
        </p>
      ),
    },
    {
      id: 'fonts',
      title: 'Fonts',
      body: (
        <p>
          This website uses Barlow, Barlow Condensed and Silkscreen, each licensed under the{' '}
          <Ext href="https://openfontlicense.org">SIL Open Font License 1.1</Ext>.
        </p>
      ),
    },
    {
      id: 'store-media',
      title: 'Store media',
      body: (
        <>
          <p>All media submitted to the Solana dApp Store was created by {COMPANY} for this application:</p>
          <ul>
            <li>screenshots, captured from the actual app;</li>
            <li>video, recorded from the actual app;</li>
            <li>the app icon and banner.</li>
          </ul>
        </>
      ),
    },
    {
      id: 'trademarks',
      title: 'Trademarks',
      body: (
        <p>
          Solana, Solana Mobile, Seeker, Saga and the Solana dApp Store are trademarks of their respective owners, as
          are Phantom, Solflare, Backpack, Discord and X. Their use here is descriptive only and doesn't imply any
          endorsement of Diggle.
        </p>
      ),
    },
    {
      id: 'reporting',
      title: 'Reporting infringement',
      body: (
        <p>
          If you believe something in Diggle infringes your rights, email <MailLink email={EMAIL} /> with the details and we'll look into
          it.
        </p>
      ),
    },
  ],
};

export const DIGGLE_DOCS: Record<DiggleDocType, LegalDocument> = { privacy, terms, license, copyright };
